name: "mlinvitrotox-tutorial"
# WARNING : As Renku makes use of mamba for more efficient package builds, please use the popular "conda-forge" channel
# For more details : https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#mixing-the-defaults-and-conda-forge-channels
# Using the defaults channel from Anaconda can easily result in getting your
# laptop, CI pipeline, etc. blacklisted by Anaconda which makes building packages
# impossible. To get permission to use Anaconda again you need to either pay or prove that
# you meet the requirements for a free license. Using the conda-forge channel avoids 
# these restrictions completely.
channels:
  - conda-forge
dependencies:
  - numpy==1.26.4
  - pandas==2.2.2
  - scipy==1.13.1
  - pyyaml>=6.0.1
  - matplotlib>=3.9.0
  - plotly==5.22.0
  - seaborn==0.13.2
  - scikit-learn==1.5.0
  - xgboost==2.0.3
  - imbalanced-learn==0.12.3
  - filetype==1.2.0
  - tqdm>=4.66.4
  - pip
  - pip:
      - streamlit==1.35.0
      - cdk-pywrapper>=0.1.0 
      - openbabel-wheel>=3.1.1.19   # rye package can only install this and not openbabel directly
      - mlinvitrotox>=0.3.3
prefix: "/opt/conda"
